### ISSUE TITLE
[Q] Will it run on a server-less environment?

### ISSUE THREAD

**Issue by rraallvv** [Crowndev/Twitter-Tip#2]
I'm talking about something like firebase, and other hosting services with readonly filesystems.

Keep up the good work.

**Comment by hypermoist** [comment]
Currently it doesn't run at all, it needs to be fixed some code isn't
updated, but I'll retry setting it up this week if I can to try get it
running on a normal server and if it works then I'll try a serverless
environment but I have doubts

**Comment by rraallvv** [comment]
Thanks for your quick response!
